# Generated by Django 2.1.4 on 2018-12-14 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fooo', '0003_genre'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True, null=True, verbose_name='slug'),
        ),
    ]
