# Generated by Django 2.1.4 on 2018-12-16 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fooo', '0005_category_end_element'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='list_of_names',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
